# Generated by Django 5.2.7 on 2025-12-05 17:30

import datetime
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faculty_name', models.CharField(max_length=50, validators=[django.core.validators.RegexValidator('^[A-Za-z ]+$', 'Only letters and spaces are allowed.')])),
                ('batch_details', models.CharField(blank=True, max_length=20, null=True)),
                ('subjects', models.JSONField(blank=True, default=list)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='student_images/')),
                ('studentname', models.CharField(max_length=50, validators=[django.core.validators.RegexValidator('^[A-Za-z ]+$', 'Only letters and spaces are allowed.')])),
                ('regno', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('batchtime', models.CharField(blank=True, max_length=30, null=True)),
                ('course', models.CharField(max_length=500)),
                ('date_of_joining', models.DateField(blank=True, null=True)),
                ('dob', models.DateField(blank=True, null=True)),
                ('father_name', models.CharField(blank=True, max_length=50, null=True, validators=[django.core.validators.RegexValidator('^[A-Za-z ]+$', 'Only letters and spaces are allowed.')])),
                ('facultyname', models.CharField(blank=True, max_length=50, null=True, validators=[django.core.validators.RegexValidator('^[A-Za-z ]+$', 'Only letters and spaces are allowed.')])),
                ('address', models.CharField(blank=True, max_length=300, null=True)),
                ('batch_started_date', models.DateField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, validators=[django.core.validators.EmailValidator()])),
                ('contact', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator('^\\+?\\d{10,15}$', 'Enter a valid contact number with 10–15 digits.')])),
                ('parent_contact', models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator('^\\+?\\d{10,15}$', 'Enter a valid contact number (10–15 digits).')])),
                ('reason', models.TextField(blank=True, null=True)),
                ('hallticket_no', models.TextField(blank=True, null=True)),
                ('Exam_Course', models.TextField(blank=True, null=True)),
                ('Certificate_status', models.TextField(blank=True, null=True)),
                ('Exam_Date', models.TextField(blank=True, null=True)),
                ('Issued_status', models.TextField(blank=True, null=True)),
                ('total_fees', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=20)),
                ('date', models.DateField()),
                ('batch_time', models.CharField(blank=True, max_length=20, null=True)),
                ('subject', models.CharField(blank=True, max_length=100, null=True)),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='page.faculty')),
            ],
        ),
        migrations.CreateModel(
            name='FeeReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_no', models.CharField(blank=True, max_length=50, null=True)),
                ('total_fees', models.PositiveIntegerField(default=0)),
                ('paid_fees', models.PositiveIntegerField(default=0)),
                ('due_fees', models.PositiveIntegerField(default=0)),
                ('amount', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('date', models.DateField(default=datetime.date.today)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='page.student')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Break',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('reason', models.TextField(blank=True, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='breaks', to='page.student')),
            ],
            options={
                'ordering': ['-from_date'],
            },
        ),
    ]
